{% set name = "flask-ldap3-login" %}
{% set version = "0.9.14" %}
{% set hashtype = "sha256" %}
{% set hash = "e11fb6752d3bbe418ec460c012335aef39e2c6645500171cc5507d2fb28df0d6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hashtype }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - enum34  # [py2k]
    - flask
    - flask-wtf
    - ldap3 >=2.0.7
    - wtforms

test:
  imports:
    - {{ name.replace('-', '_') }}

about:
  home: https://github.com/nickw444/flask-ldap3-login
  license: MIT
  license_file: LICENSE
  dev_url: http://flask-ldap3-login.readthedocs.io/en/latest/
  doc_url: https://github.com/nickw444/flask-ldap3-login
  summary: LDAP3 Logins for Flask/Flask-Login
  description: |
    Flask LDAP3 Login allows you to easily integrate your flask app with an
    LDAP directory. It can be used as an extension to Flask-Login and can
    even be used with Flask-Principal for permission and privilege
    management.

extra:
  recipe-maintainers:
    - ericdill
