{% set name = "flask-ldap3-login" %}
{% set version = "0.9.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flask-ldap3-login-{{ version }}.tar.gz
  sha256: 3b98eff48f94cf8bcf91c1790eb3a59e03df6c56d5e1bd8fe8919193d120fb5a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flask
    - flask-wtf
    - ldap3 >=2.0.7
    - python >=3.6
    - wtforms >=1.0.2

test:
  imports:
    - flask_ldap3_login
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nickw444/flask-ldap3-login
  license: MIT
  license_file: LICENSE
  dev_url: http://flask-ldap3-login.readthedocs.io/en/latest/
  doc_url: https://github.com/nickw444/flask-ldap3-login
  summary: LDAP3 Logins for Flask/Flask-Login
  description: |
    Flask LDAP3 Login allows you to easily integrate your flask app with an
    LDAP directory. It can be used as an extension to Flask-Login and can
    even be used with Flask-Principal for permission and privilege
    management.

extra:
  recipe-maintainers:
    - ericdill
