# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "bnMME2oDMp1YEpkl7smfwyhe3AJjqmIDoZZ+wCTEYAocOJW5gryHksQ/blqUR0wlABaMD3Dsi0rGzX+Rm8ZHQ3Jnf6ydfJRkRMTszWYZyv9W4mmbau9on8b7bl4OPTZEXSnK6dQiQcKUbLsqNgcV6QxmKfDjDxcnkx9k6yfJXd59Z5TerfdBQXdsOl6tc87Lb8JPSD6HsZb8+iEfzqgtEk0qQwnrGoAuOqSsT2nMzZpeuLbFa5EOKgUWmX+3K21D2l8x4AN7j+3kNa/A6FRvqiuUmc2YHviRB+2Qb6Q4WofKB/6tjM35X1kEmCvhdPmdhhXSEqg74aJ7bAt7q+IyyNYk28M3EtMlgGs3NhoUMVKXB9waSfTmknCqErSif0lprFUZ/DBvfkkuXoG/I67TmMbWb7qIo8MS7MYK/pYQv7PUpFURYO7apds8Dpsw7xQ5wqF8fARrIsRgCy6IwjBeaM7S+Xas4NVvsI4yJ+vvVFfMxYtzSaYa76d/rnZWiwabE7mETZeEcPJDns4S+iTOU3UCWVcKMUAlBo06EnXdvxVdsDTo+1IghTBvuxRo+O1Sh1i5uIvaG84+9q0fCH3rFhR6mkbOHjp5FujWW6uFTHkmzm2I4AgIXq5GBlj8zbpMp/ZA3RPglNSoH5P3K5FeZm+yZxJOVMlfbAyiD/fbFC0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
