travis:
  secure:
    BINSTAR_TOKEN: bnMME2oDMp1YEpkl7smfwyhe3AJjqmIDoZZ+wCTEYAocOJW5gryHksQ/blqUR0wlABaMD3Dsi0rGzX+Rm8ZHQ3Jnf6ydfJRkRMTszWYZyv9W4mmbau9on8b7bl4OPTZEXSnK6dQiQcKUbLsqNgcV6QxmKfDjDxcnkx9k6yfJXd59Z5TerfdBQXdsOl6tc87Lb8JPSD6HsZb8+iEfzqgtEk0qQwnrGoAuOqSsT2nMzZpeuLbFa5EOKgUWmX+3K21D2l8x4AN7j+3kNa/A6FRvqiuUmc2YHviRB+2Qb6Q4WofKB/6tjM35X1kEmCvhdPmdhhXSEqg74aJ7bAt7q+IyyNYk28M3EtMlgGs3NhoUMVKXB9waSfTmknCqErSif0lprFUZ/DBvfkkuXoG/I67TmMbWb7qIo8MS7MYK/pYQv7PUpFURYO7apds8Dpsw7xQ5wqF8fARrIsRgCy6IwjBeaM7S+Xas4NVvsI4yJ+vvVFfMxYtzSaYa76d/rnZWiwabE7mETZeEcPJDns4S+iTOU3UCWVcKMUAlBo06EnXdvxVdsDTo+1IghTBvuxRo+O1Sh1i5uIvaG84+9q0fCH3rFhR6mkbOHjp5FujWW6uFTHkmzm2I4AgIXq5GBlj8zbpMp/ZA3RPglNSoH5P3K5FeZm+yZxJOVMlfbAyiD/fbFC0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
