appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: c1BvNe+DEa5K1yThzf+TSQxfQB/runlHmX/2W2ur3YYnOXD9cBgmJC14mAfkDZEbVXBIFfy0TQcsuYzjtQCR2GH+PJZNCXQBkoebxVGVjKILE6QArOpmn3bQz3sB7eg42KSEu6F96GrQ/bGyYQu6RI+UF8CS+FMxcGxkBC2xogaHhwoaGPLLyE8sZo1fIPTozx6nQn8HtURa2zHpCZjxiU7co8aJtYiovuUbwj3hPx+spg829Hvtk30achCrGvnOBlKxZkLBMULPFbj7VUQzIYAQMXAu5CHPnKJ0TGybEXFdmQ/haky7kTX69qgqnYcfxuakJ+St5VNgaECqnhv+T2LXlyaXH5rqlMUplOZyeri929PqaG52FFW86AOu1tnH5aEmMC3IAfaQ09POQgHKt03/M/8Re7CkdFmzywWjaANclVZo5GCn6SxW5iLqWw6bJUe5iOGjB283Tu+KtAUEggRG5ksYTFd3kzhuRPQSkGvAH7FZwHUU/6LCC8llwLZKhQj4ZeRuyPMoJIDi+Pn+32L629MVaORI69AkqMbkVcteJSHVvWU1Lac0NK15kHx4cJi68Ymdi5ICwbRyK8HBV7NO/G+bpx/qI3SLlzJlyxGxfSjdB9z7iAFLuTQKbZZ3eQ7Wf8bIxCQ/Y/I05rKRsWcDeXOGmTKhE93q7YcItgs=}
provider:
  win: azure
conda_forge_output_validation: true
